resources:
  - name: incoming_webhook
    type: IncomingWebhook
    configuration:
      webhookName: IncomingWebhookIntegration

pipelines:
  - name: release_demo_pipeline
    steps:
      - name: Processing_Incoming_Webhook
        type: Bash
        configuration:
          affinityGroup: Cloud_Automation_Webhook
          inputResources:
            - name: incoming_webhook
        execution:
          onExecute:
            - |
              payload=$(cat <<-END
                {
                  "data": {
                    "project": "$pr",
                    "stage": "$st",
                    "service": "$sv",
                    "status": "succeeded",
                    "result": "pass",
                    "deployment": {
                      "jfrogUrl": "$step_url"
                    },
                    "labels": {
                      "jfrogUrl": "$step_url"
                    }
                  },
                  "source": "jfrog-pipeline",
                  "specversion": "1.0",
                  "type": "sh.keptn.event.deployment.finished",
                  "shkeptncontext": "$sh",
                  "triggeredid": "$id"
                }
              END
              )
              echo "payload = $payload"
            - echo "$res_incoming_webhook_payload" | jq '.' > payload.json
            - |
              add_run_variables event_payload="$(jq -n \
              --arg pr $(read_json payload.json "project") \
              --arg st $(read_json payload.json "stage") \
              --arg sv $(read_json payload.json "service") \
              --arg sh $(read_json payload.json "shkeptncontext") \
              --arg id $(read_json payload.json "id") \
              $payload
            - echo "$event_payload"

      - name: Send_Finish_Event
        type: Bash
        configuration:
          affinityGroup: Cloud_Automation_Webhook
          integrations:
            - name: rob00334Cred
          inputSteps:
            - name: Processing_Incoming_Webhook
        execution:
          onExecute:
            - 'curl -X POST "$int_rob00334Cred_BASE_URL/api/v1/event" -H "accept: application/json" -H "x-token: $int_rob00334Cred_API_TOKEN" -H "Content-Type: application/json" -d "$event_payload"'
