apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "release-demo"
spec:
  stages:
  - name: staging
    sequences:
    - name: release
      tasks:
      - name: test
  - name: staging1
    sequences:
    - name: release
      tasks:
      - name: notify
      - name: deployment
      - name: test
      - name: evaluation
        properties:
          timeframe: "5m"
      - name: updateissue
  - name: production
    sequences:
    - name: release
      triggeredOn:
      - event: staging1.release.finished
      tasks:
      - name: approval
        properties:
          pass: manual
          warning: manual
      - name: deployment
      - name: test
      - name: evaluation
        properties:
          timeframe: "5m"
