apiVersion: spec.keptn.sh/0.2.0
kind: Shipyard
metadata:
  name: "release-demo"
spec:
  stages:
  - name: staging
    sequences:
    - name: release
      tasks:
      - name: notify
      - name: evaluation
        properties:
          timeframe: "5m"
      - name: updateissue
  - name: production
    sequences:
    - name: release
      triggeredOn:
      - event: staging.release.finished
      tasks:
      - name: approval
        properties:
          pass: automatic
          warning: automatic
      - name: test
      - name: evaluation
        properties:
          timeframe: "5m"
