apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.notify.triggered
      requests:
        - curl --request POST --data
          '{"project":"{{.data.project}}","service":"{{.data.service}}","stage":"{{.data.stage}}","type":"{{.type}}","jiraKey":"{{.data.release.jiraKey}}","jiraSummary":"{{.data.release.jiraSummary}}","jiraUrl":"{{.data.release.jiraUrl}}"}'
          https://webhook.site/2be34b4b-8a90-47cd-ba9f-a3e237e90765
      subscriptionID: a8c2b213-4eb3-4d4d-950c-f2fad8c07048
      sendFinished: true
    - type: sh.keptn.event.notify.triggered
      requests:
        - "curl --request POST --data 'payload={  \"blocks\":
          [    {      \"type\" : \"section\",      \"text\" : {        \"type\":
          \"mrkdwn\",        \"text\" : \"New JIRA ticket
          {{.data.release.jiraKey}} to Deploy Code
          Created\"      }    },    {      \"type\" : \"section\",      \"text\"
          : {        \"type\": \"mrkdwn\",        \"text\" : \"*Project:*
          {{.data.project}}\\n*Service:* {{.data.service}}\\n*Stage:*
          {{.data.stage}}\\n*Type:* {{.type}}\\n*jiraSummary*:
          {{.data.release.jiraSummary}}\\n*jiraUrl*:
          {{.data.release.jiraUrl}}\\n*Bridge:*
          {{.env.secret_slackwebhook_bridgeUrl}}/trace/{{.shkeptncontext}}\"      \
          }    }  ]}'
          https://hooks.slack.com/services/{{.env.secret_slackwebhook_token}}"
      envFrom:
        - name: secret_slackwebhook_token
          secretRef:
            name: slack-webhook
            key: token
        - name: secret_slackwebhook_bridgeUrl
          secretRef:
            name: slack-webhook
            key: bridgeUrl
      subscriptionID: 3d8bc3a4-9726-4721-b54a-c71577d803bd
      sendFinished: true
    - type: sh.keptn.event.deployment.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"project\":\"{{.data.project}}\",\"service\
          \":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"shkeptnconte\
          xt\":\"{{.shkeptncontext}}\",\"id\":\"{{.id}}\"}'
          https://{{.env.secret_jfrog_WEBHOOKURL}}"
      envFrom:
        - name: secret_jfrog_WEBHOOKURL
          secretRef:
            name: jfrog
            key: WEBHOOKURL
      subscriptionID: 246b27aa-8f04-47ab-877f-1f10e4ec0a0a
      sendFinished: false
    - type: sh.keptn.event.test.triggered
      requests:
        - "curl --header 'Authorization: token
          {{.env.secret_githubsecret_GITHUBTOKEN}}' --request POST --data
          '{\"event_type\":\"test\",\"client_payload\":{\"type\":\"{{.type}}\",\
          \"project\":\"{{.data.project}}\",\"service\":\"{{.data.service}}\",\
          \"stage\":\"{{.data.stage}}\",\"shkeptncontext\":\"{{.shkeptncontext}}\
          \",\"id\":\"{{.id}}\"}}'
          https://api.github.com/repos/dt-robertjahn/rob00334-release-demo/disp\
          atches"
      envFrom:
        - name: secret_githubsecret_GITHUBTOKEN
          secretRef:
            name: github-secret
            key: GITHUBTOKEN
      subscriptionID: 690a761a-dda0-4305-9513-aaf5571cef0e
      sendFinished: false
    - type: sh.keptn.event.updateissue.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"jiraKey\":\"{{.data.release.jiraKey}}\",\"jiraMessage\":\"SLO
          Evaluation for Project: {{.data.project}} Stage: {{.data.stage}}
          Service:
          {{.data.service}}\",\"result\":\"{{.data.result}}\",\"bridge\":\"{{.e\
          nv.secret_bridge_url}}/evaluation/{{.shkeptncontext}}/{{.data.stage}}\
          \"}'
          https://automation.atlassian.com/pro/hooks/9be53cf516a9e3e0af08d3bd0c\
          c215d77c0b985e"
      envFrom:
        - name: secret_bridge_url
          secretRef:
            name: bridge
            key: url
      subscriptionID: 812e6b75-079a-4331-88dd-9e92fc70f9de
      sendFinished: true
    - type: sh.keptn.event.gitlab.triggered
      requests:
        - "curl --header 'Private-Token: {{.env.secret_gitlab_accesstoken}}'
          --header 'Content-Type: application/json' --request POST --data
          '{\"ref\":\"master\",\"variables\":[{\"key\":\"CA_PROJECT\",\"value\":\
          \"{{.data.project}}\"},{\"key\":\"CA_STAGE\",\"value\":\"{{.data.stag\
          e}}\"},{\"key\":\"CA_SERVICE\",\"value\":\"{{.data.service}}\"},{\"key\
          \":\"CA_SHKEPTNCONTEXT\",\"value\":\"{{.shkeptncontext}}\"},{\"key\":\
          \"CA_ID\",\"value\":\"{{.id}}\"}]}'
          https://gitlab.com/api/v4/projects/dt-alliances/webhook-demo/pipeline"
      envFrom:
        - name: secret_gitlab_accesstoken
          secretRef:
            name: gitlab
            key: access-token
      subscriptionID: 26efbe45-9ca5-4ac7-bc4d-18d11048aeae
      sendFinished: false
