apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - "curl --header 'Content-type: application/json' --request POST --data
          '{\"type\":\"{{.type}}\",\"project\":\"{{.data.project}}\",\"service\
          \":\"{{.data.service}}\",\"stage\":\"{{.data.stage}}\",\"shkeptnconte\
          xt\":\"{{.shkeptncontext}}\",\"id\":\"{{.id}}\"}'
          https://{{.env.secret_jfrog_WEBHOOKURL}}"
      envFrom:
        - name: secret_jfrog_WEBHOOKURL
          secretRef:
            name: jfrog
            key: WEBHOOKURL
      subscriptionID: 246b27aa-8f04-47ab-877f-1f10e4ec0a0a
      sendFinished: false
